"""Renders, for the second installation of Study 2, when the radar reported the
person sitting between the sensor and the doorway: one row per trial, time in
the trial along the axis. Output is a pgfplots figure body on stdout, in the
style of the thesis's other plots.

Each frame falls into one of three classes, as in seated_dropouts() of
analyse_privacy_switch.py:
  reported    a target within the seat radius of the baseline position
  shifted     not at the seat, but another target within 1 m of it: most
              likely the same person reported a little off their usual place
  lost        not at the seat and nobody within 1 m of it

    python3 scripts/render_seated_timeline.py > <thesis>/figures/seated-timeline.tex
"""

import math
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import analyse_privacy_switch as analysis

CSV = os.path.join(ROOT, "study", "privacy_switch_study2_holdout.csv")
XMAX = 30.0          # seconds shown; later frames in the three long trials are all "reported"
NEAR_M = 1.0         # a gap with another target this close to the seat counts as shifted
FILL = {"reported": "seatc!35", "shifted": "black!30", "lost": "lossc"}


def classes(x, seat):
    """Frame times and classes for one trial."""
    frames = x["frames"]
    seen = [any(analysis.near_seat(t, seat) for t in f["targets"]) for f in frames]
    out = ["reported"] * len(frames)
    i = 0
    while i < len(frames):
        if seen[i]:
            i += 1
            continue
        j = i
        while j < len(frames) and not seen[j]:
            j += 1
        near = [math.hypot(t["x"] - seat["median_x_mm"], t["y"] - seat["median_y_mm"]) / 1000
                for f in frames[i:j] for t in f["targets"]]
        cls = "shifted" if near and min(near) <= NEAR_M else "lost"
        out[i:j] = [cls] * (j - i)
        i = j
    t0 = frames[0]["t"]
    return [f["t"] - t0 for f in frames], out


def runs(times, cls):
    """(start, end, class) runs; a frame lasts until the next one, the last for 0.1 s."""
    out, start = [], 0
    for k in range(1, len(times) + 1):
        if k == len(times) or cls[k] != cls[start]:
            end = times[k] if k < len(times) else times[-1] + 0.1
            out.append((times[start], end, cls[start]))
            start = k
    return out


def main():
    rows, logs, door = analysis.load(CSV, None)
    baselines = analysis.load_baselines(CSV)
    res = [analysis.analyse_trial(r, logs[r["trial_id"]], door) for r in rows if r["trial_id"] in logs]
    res.sort(key=lambda x: int(x["id"]))

    body, long_trials = [], []
    for x in res:
        seat = analysis.seat_of(logs[x["id"]], baselines)
        if not seat:
            continue
        y = int(x["id"])
        times, cls = classes(x, seat)
        for a, b, c in runs(times, cls):
            if a >= XMAX:
                continue
            body.append(f"      \\fill[{FILL[c]}] (axis cs:{a:.2f},{y - 0.38:.2f}) rectangle "
                        f"(axis cs:{min(b, XMAX):.2f},{y + 0.38:.2f});")
        if times[-1] > XMAX:
            long_trials.append((y, times[-1]))

    n = len(res)
    print("% when the radar reported the seated person, second installation of Study 2")
    print("% generated by scripts/render_seated_timeline.py -- regenerate rather than edit")
    print("\\definecolor{seatc}{HTML}{2A78D6}%")
    print("\\definecolor{lossc}{HTML}{EB6834}%")
    print("\\begin{tikzpicture}")
    print("  \\begin{axis}[")
    print("      width=0.92\\textwidth, height=8.5cm, scale only axis=false,")
    print(f"      xmin=0, xmax={XMAX:g}, ymin=0.4, ymax={n + 0.6}, y dir=reverse,")
    print("      xtick={0,5,...,30}, ytick={1,10,20,30,40,50},")
    print("      xlabel={Time in trial (s)}, ylabel={Trial},")
    print("      tick label style={font=\\footnotesize}, label style={font=\\footnotesize},")
    print("      xmajorgrids, grid style={line width=0.2pt, draw=black!12},")
    print("      axis line style={draw=black!45}, tick style={draw=black!45},")
    print("      clip=false,  % bars stop at XMAX already; the labels for the long trials sit outside")
    print("      legend columns=3, legend cell align=left,")
    print("      legend style={at={(0.5,1.02)}, anchor=south, draw=none, font=\\footnotesize,")
    print("                    /tikz/every even column/.append style={column sep=0.6em}},")
    print("    ]")
    print("      \\addlegendimage{area legend, fill=seatc!35, draw=none}\\addlegendentry{reported at the seat}")
    print("      \\addlegendimage{area legend, fill=black!30, draw=none}\\addlegendentry{reported about 0.5\\,m from it}")
    print("      \\addlegendimage{area legend, fill=lossc, draw=none}\\addlegendentry{not reported, nobody near}")
    print("\n".join(body))
    for y, total in long_trials:
        print(f"      \\node[anchor=west, font=\\scriptsize, text=black!60, inner sep=1pt] "
              f"at (axis cs:{XMAX:g},{y}) {{$\\rightarrow$ {total:.0f}\\,s}};")
    print("  \\end{axis}")
    print("\\end{tikzpicture}%")


if __name__ == "__main__":
    main()
